name: Public STranslate

# https://github.com/softprops/action-gh-release/issues/236#issuecomment-1150530128
# 无需 Token 即可发布
permissions:
  contents: write

on:
  release:
    types: [published]
  push:
    tags:
      - "*" # Push events to matching *, i.e. 1.0, 20.15.10

jobs:
  # 以下为构建工作流
  build:
    runs-on: windows-latest # 添加EnableWindowsTargeting可支持跨平台编译WPF项目
    # TODO: job 之间传递参数
    # outputs:
      # fileHash: ${{ steps.calculate_hash.outputs.hash }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.0.9'

    - name: Publish
      run: |
        .\publish.ps1
        .\7z.ps1 ${{ github.ref_name }}

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ github.ref_name }}
        body_path: CHANGELOG.md
        draft: false # 设置为 false 可立即发布版本
        files: |
          LangIndicator_${{ github.ref_name }}_win-x64_7z.7z
          LangIndicator_${{ github.ref_name }}_win-x64_sha256.txt
